In [1]:
#from nested_dict import *
from collections import defaultdict
import numpy as p

In [3]:
d={'a':2}
d.update({'a':1})
d

{'a': 1}

In [15]:
from collections import defaultdict

# and then the miracle occurs:

def make_dict(): 
    return defaultdict(make_dict)

mydict = make_dict()

mydict['coords'] = [(1,2),(3,4)]
mydict['colors'] = ['blue', 'red']
mydict['labels'] = ['A', 'B']

type(mydict)

collections.defaultdict

In [27]:
d = {1: [0], 2: [0,0], 3: [0,0,0]}
#d[1].append(1)  # AttributeError: 'int' object has no attribute 'append'

dd = defaultdict(list)
for k, v in d.iteritems(): 
    for i in v:
        dd[k].append(i)
dd[1].append(2)
dd[1].remove(2)
dd

defaultdict(<type 'list'>, {1: [0], 2: [0, 0], 3: [0, 0, 0]})

In [6]:
d = {}
try: d[1] += 1
except: d[1] = 1
d

{1: 1}

In [ ]:
meter_pow_list = [(1, 3.4),(1, 3.4),(2, 3.4),(2, 3.4),(3, 3.4),(4, 3.4)]

factors = { 1: 10, 2: 20, 3:50, 4: 100 }


def reduce_to_meters(meter_pow_list):
    dd = {}
    for meter, power in meter_pow_list: 
        try:dd[meter] += power
        except: dd[meter] = power
    return dd



def reduce_to_weighted_sum(dd, factors):
    weightedSum = 0
    for key, val in dd.iteritems():
        weightedSum += val*factors[key] 
    return weightedSum


reduce_to_weighted_sum( reduce_to_meters( meter_pow_list), factors) # => 714.0

In [12]:
colors, labels, coords = mydict['colors'], mydict['labels'], mydict['coords']
print colors
['&markers=color:'+color+'%7Clabel:'+labels[0]+'%7C'+str(coords[0][0])+','+str(coords[0][1]) for color in colors]

['blue', 'red']


['&markers=color:blue%7Clabel:A%7C1,2', '&markers=color:red%7Clabel:A%7C1,2']

In [2]:
from collections import namedtuple
Point = namedtuple('Point', 'x y')
pt1 = Point(1.0, 5.0)
pt2 = Point(2.5, 1.5)

from math import sqrt
sqrt((pt1.x-pt2.x)**2 + (pt1.y-pt2.y)**2)

3.8078865529319543

In [2]:
x =[1,2]
y= [3,4]
d = defaultdict(list)
d =dict(zip(x,y))
d

{1: 3, 2: 4}

In [13]:
as_tuple = lambda C : tuple(tuple(C[i]) for i in range(3))

#def hashable(C): 
#    if C.shape[1] > 1 :
#        return tuple((hashable(C[i])) for i in range(C.shape[0]))
#    else : return tuple(C)

In [14]:
C=p.array([[0,2,1],[1,0,2],[1,2,0]])
#tuple(tuple(C[i]) for i in len(C))
#tuple(C[0])
D=as_tuple(C)
hash(D)

3916253770447430313

In [15]:
list_of_minimal_normal = [p.array([[0,2,1],[1,0,2],[1,2,0]]), \
                          p.array([[0,2,1],[1,0,2],[1,2,0]]), \
                          p.array([[0,3,2],[2,0,3],[2,3,0]])]
list_of_indices = [(2,1), (3,1,4), (3,1,5)]

#hashzip = lambda list_keys, list_values : dict(zip([to_hash(k) for k in list_keys], list_values))
#same as
#hashzip = lambda list_keys, list_values : dict(zip(imap(hashable, list_keys), list_values))

#print hashzip(list_of_minimal_normal , list_of_indices).items()

In [20]:
from itertools import *
def defhashzip(list_keys, list_values):
    d = defaultdict(list)
    for (C, index) in zip(list_keys, list_values):
        C_as_tuple = as_tuple(C)
        #d.update({quasicone : index})
        d[C_as_tuple].append(index) # quasicone must be hashable then
    return d
T = dict(defhashzip(list_of_minimal_normal , list_of_indices).items())
#for k in T:
#    print(k)
print(T)

{((0, 2, 1), (1, 0, 2), (1, 2, 0)): [(2, 1), (3, 1, 4)], ((0, 3, 2), (2, 0, 3), (2, 3, 0)): [(3, 1, 5)]}


In [21]:
#%timeit hashzip(list_of_minimal_normal , list_of_indices)

In [ ]:
#%timeit defhashzip(list_of_minimal_normal , list_of_indices)

In [9]:
i, j = 2, 0
zip(*(_Gap.get(i, 0) for i in subdiag_indices_iter(i,j)))
== {_Gap.get(i, 0) : index for index in subdiag_indices_iter(i,j)}

SyntaxError: invalid syntax (<ipython-input-9-3210647581b7>, line 3)

In [21]:
for C, index_list in T.iteritems():
    print p.array(C), " --> ",index_list


[[0 2 1]
 [1 0 2]
 [1 2 0]]  -->  [(2, 1), (3, 1, 4)]
[[0 3 2]
 [2 0 3]
 [2 3 0]]  -->  [(3, 1, 5)]


In [18]:
for k, index_list in T.items():
    for i, index in enumerate(index_list):
        if index[0] == 3:
            del index_list[i
print T.items()

[(((0, 2, 1), (1, 0, 2), (1, 2, 0)), [(2, 1)]), (((0, 3, 2), (2, 0, 3), (2, 3, 0)), [])]


In [23]:
for C in T.keys():
    T[C].insert(0, True)
print T.items()

[(((0, 2, 1), (1, 0, 2), (1, 2, 0)), [True, (2, 1), (3, 1, 4)]), (((0, 3, 2), (2, 0, 3), (2, 3, 0)), [True, (3, 1, 5)])]


In [31]:
from collections import deque

list1 = [1,2,3,4,5]
newlist = deque(list1)
newlist.append(6)
print newlist[2], list1

3 [1, 2, 3, 4, 5]


In [57]:
list0 =[0,0,0,0,0,0]
print list0 
print any(list0)

[0, 0, 0, 0, 0, 0]
False


In [36]:
%timeit x = list1[0] = 0

10000000 loops, best of 3: 71.9 ns per loop


In [24]:
counter = 0
#while True:
#    counter += 1
#    print "1"
#    if counter == 4 :
        if  raw_input("ENTER to continue") == '':
            counter = 0
            continue
        else: 
            print "ende"
            break


IndentationError: unexpected indent (<ipython-input-24-f96608432bab>, line 6)

In [11]:
l=range(5)
las = l[-1]
for i in range(las +1):
    l[-1] = i
    print str(l)


[0, 1, 2, 3, 0]
[0, 1, 2, 3, 1]
[0, 1, 2, 3, 2]
[0, 1, 2, 3, 3]
[0, 1, 2, 3, 4]


In [27]:
cd Documents/Doctoral_Thesis/Python


/home/thomas/Documents/Doctoral_Thesis/Python


In [70]:
import pickle
inputfile = "tree_for_graph_r4"
with open(inputfile, "r") as file: Tree = pickle.load(file)
#print type(Tree)
#from Tree_to_TikZ_Graph import *
#Output_as_Graph(Tree_to_TeX(Tree))

In [34]:
total = 100
list1 = [3, 4]   


result = 0
for i in range(1,total):
    for val in list1:
        if i % val == 0:
            result +=1
            break # break the inner loop
print result


'''For a list like 

    list1 = [5, 7, 15, 21, 44, 39, 91] 

I would reduce 15 and 21'''

49


In [31]:
dictionary={'sca4': [['BM1', 17], ['BM2', 33]], 'sca6': [['GM2', 46], ['GM2', 67]]}
textfile = '''
sca4 15 25
sca4 20 32
sca6 45 62
'''

col1, col2, col3 = [],[],[]
for i, line in enumerate(textfile.split("\n")):
    if not line.strip():
        continue
    line_as_list = line.strip().split(" ")
    col1.append(line_as_list[0]), col2.append(line_as_list[1]), col3.append(line_as_list[-1])
    
def multiples_removed( oldlist):
    newlist = []
    prev = None
    for el in oldlist:
        if el != prev: newlist.append(el)
        prev = el
    return newlist

col1 = multiples_removed(col1)

for specifier in col1:
    is_valid = "wrong"
    for value_list in dictionary.get(col1, [[]]):
        if int(col2) <= value_list[1] <= int(col3):
            print value_list
            print "correct"
        else:
            print is_valid

['BM1', 17]
correct
wrong
wrong
wrong
['GM2', 46]
correct
wrong


In [61]:
#my original question was devoted to the fact that the vectorization is doing an internal type-cast and how much this would affect performance. So here is the answer:
#    It does, but not with only <23% not the considerabel effect I supposed.


#y = np.int_([1,2,4])

import numpy as np

def triv(a, b): return tuple([a, b])

triv_vec = np.vectorize(triv, otypes = [np.int, np.int])

v1 = np.random.random_integers(-5, high = 5, size = 100000)
v2 = np.random.random_integers(-5, high = 5, size = 100000)

%timeit [tuple([i,j]) for i,j in zip(v1,v2)] # ~ 596 µs per loop

%timeit triv_vec(v1, v2) # ~ 544 µs per loop

#%timeit map(triv, v1, v2) # ~ 64.4 ms per loop


10 loops, best of 3: 67.5 ms per loop
10 loops, best of 3: 51.9 ms per loop


In [117]:
import math

  
def root(fnc, a, b, eps = 1e-8, maxtimes = None):
    if maxtimes == None: maxtimes = (int)(0.1+math.ceil(math.log((b-a)/eps, 2.0)+2))
    for counter in xrange(maxtimes+1) : # a was assumed negative and b positive
        if fnc(a) > -eps : return a
        if fnc(b) < eps : return b
        new_bound = (a + b)/2.0
        print a, b, new_bound
        if fnc(new_bound) < 0 : a = new_bound
        else : b = new_bound
    return tuple([new_bound, min(-fnc(a),fnc(b))])
            


fnc = lambda x : x**3-x-0.1
result = root(fnc, 0, 2)
print "root = ", result, "error = ", result[1] #print fnc.counter, fnc.maxtimes

#import numpy
#[x*x*x-x-0.1 for x in numpy.arange(0, 2, 0.2)]

0 2 1.0
1.0 2 1.5
1.0 1.5 1.25
1.0 1.25 1.125
1.0 1.125 1.0625
1.0 1.0625 1.03125
1.03125 1.0625 1.046875
1.03125 1.046875 1.0390625
1.0390625 1.046875 1.04296875
1.04296875 1.046875 1.044921875
1.044921875 1.046875 1.0458984375
1.0458984375 1.046875 1.04638671875
1.04638671875 1.046875 1.04663085938
1.04663085938 1.046875 1.04675292969
1.04663085938 1.04675292969 1.04669189453
1.04663085938 1.04669189453 1.04666137695
1.04666137695 1.04669189453 1.04667663574
1.04667663574 1.04669189453 1.04668426514
1.04667663574 1.04668426514 1.04668045044
1.04668045044 1.04668426514 1.04668235779
1.04668045044 1.04668235779 1.04668140411
1.04668045044 1.04668140411 1.04668092728
1.04668045044 1.04668092728 1.04668068886
1.04668045044 1.04668068886 1.04668056965
1.04668045044 1.04668056965 1.04668051004
1.04668051004 1.04668056965 1.04668053985
1.04668051004 1.04668053985 1.04668052495
1.04668052495 1.04668053985 1.0466805324
root =  1.0466805324 error = 

TypeError: 'float' object has no attribute '__getitem__'

In [51]:
l = [1,1,1,3,3,3,5,5,5]

def multiples_removed( oldlist):
    newlist = []
    prev = None
    for el in oldlist:
        if el != prev: newlist.append(el)
        prev = el
    return newlist

multiples_removed(l)

1
1
1
3
3
3
5
5
5


[1, 3, 5]

In [14]:
col1, col2, col3 = [],[],[]
for i, line in enumerate(textfile.split("\n")):
    if not line.strip():
        continue
    line_as_list = line.strip().split(" ")
    col1.append(line_as_list[0]), col2.append(line_as_list[1]), col3.append(line_as_list[-1])
#    col1, col2, col3 = line.strip().split(" ")
    
for value_list in dictionary.get(col1, []):
    
    for el2, el3 in zip(col2,col3):
        if int(el2) <= value_list[1] <= int(el3):
            print "correct"
        else:
            print "wrong"

['sca4', 'sca4', 'sca6']

In [13]:
import numpy as p
from collections import defaultdict
from itertools import *
n = 3
ColumnIndexList = list(permutations( range(n+1), 2))
RowIndexList    = list(permutations( range(n+1), 3))
q = (n+2)*(n+1)
A = defaultdict(int)
A = A.fromkeys(product(RowIndexList, ColumnIndexList), 0)
for RowIndex in RowIndexList:
    A[tuple([RowIndex, tuple([RowIndex[i] for i in [0,1]])])] = 1
    A[tuple([RowIndex, tuple([RowIndex[i] for i in [2,0]])])] = 1
    A[tuple([RowIndex, tuple([RowIndex[i] for i in [2,1]])])] = -1
#print A
B = p.array([A[tuple([i,j])] for i,j in product(RowIndexList, ColumnIndexList)])
print B

[ 1  0  0  0  0  0  1 -1  0  0  0  0  1  0  0  0  0  0  0  0  0  1 -1  0  0
  1  0  1 -1  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  1  0 -1  0  0
  1  1  0 -1  0  0  0  0  0  0  0  0  1  0  0  0  1  0 -1  0  0  0  0  0  0
  1  0  0 -1  1  0  0  0  0  0  0  0  1  0  0  0  0  0 -1  1  0  1 -1  0  0
  1  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  1 -1  1  0 -1  0  0
  1  0  0  0  0  0  0  0  0  0  0  0  1  0  1 -1  0  0  0  0  0  0 -1  1  0
  1  0  0  0  0  0  0  0  0  0  0  0  1  0  0 -1  0  1 -1  1  0  0  0  0  0
  1  0  0  0  0  0  0  0  0  0  0  0  1  0  0 -1  1  0  1 -1  0  0  0  0  0
  1  0  0  0  0  0  0  0  1 -1  0  0  1  0  0  0  0  0  0 -1  0  1  0  0  0
  1  0  0  0  0  0  0  0  0 -1  0  1  1  0  0 -1  0  1  0  0  0  0  0  0  0
  1  0  0  0  0  0  0  0  0 -1  1  0  1  0  0 -1  1  0  0  0  0  0  0  0  0
  1  0  0  0  0 -1  1  0  0  0  0  0  1]


array(None, dtype=object)